server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    initial-instance-info-replication-interval-seconds: 3